# Site settings
title: "Jawa : Java, JVM et plus si affinités..."
email: bgiraudou@gmail.com
description: "Blog personnel sur Java, la JVM, Scala, Groovy, Clojure, les outils de construction comme Gradle ou Maven, le mouvement DevOps et bien plus encore."

twitter: {
	username: joowgir
}

gems:
  - jemoji